package publicquery

import (
	"context"
	"github.com/Balestrino/italian-weather-alert/internal/backend/domain"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"time"
)

// ReadTerritorialFacts shares temporal and evidence interpretation with public
// reads, but is only wired to the private administrative service. Region is
// resolved before constructing the scoped SQL; it is never a public parameter.
func ReadTerritorialFacts(ctx context.Context, pool *pgxpool.Pool, region, istat string, at time.Time) ([]RegionalWarning, []Measure, error) {
	if len(region) != 2 || region[0] < '0' || region[0] > '9' || region[1] < '0' || region[1] > '9' {
		return nil, nil, ErrInvalidParameters
	}
	if _, err := domain.New(pool).Region(ctx, region); err != nil {
		return nil, nil, err
	}
	s := New(pool)
	s.region = region
	s.scopeTime = at
	qt := QueryTime{EvaluationTime: at, KnownAt: at}
	regional, err := s.regional(ctx, istat, "", "", "", "", qt)
	if err != nil {
		return nil, nil, err
	}
	measures, err := s.measures(ctx, istat, qt)
	return regional, measures, err
}
func (s *Store) sourcesSQL() string {
	if s.region == "" {
		return "registry_public_sources"
	}
	// region consists of exactly two validated ASCII digits and timestamp is generated by time.Format.
	collect := ""
	if s.collectedOnly {
		collect = " AND src.collection_enabled"
	}
	return `(SELECT src.* FROM registry_sources src JOIN (SELECT DISTINCT ON(source_id) source_id,region_code FROM territorial_source_associations WHERE recorded_at<='` + s.scopeTime.UTC().Format(time.RFC3339Nano) + `'::timestamptz ORDER BY source_id,recorded_at DESC,id DESC) scope ON scope.source_id=src.id WHERE scope.region_code='` + s.region + `'` + collect + `)`
}

// ReadReportFacts uses the report transaction and its selected datasets. This
// private entry point never broadens public visibility or reads suspended sources.
func ReadReportFacts(ctx context.Context, tx pgx.Tx, region string, datasets map[string]string, at time.Time) ([]RegionalWarning, []Measure, []OperationalPhase, error) {
	if len(region) != 2 || region[0] < '0' || region[0] > '9' || region[1] < '0' || region[1] > '9' {
		return nil, nil, nil, ErrInvalidParameters
	}
	s := &Store{pool: tx, region: region, scopeTime: at, collectedOnly: true, snapshotDatasets: datasets}
	qt := QueryTime{EvaluationTime: at, KnownAt: at}
	w, err := s.regional(ctx, "", "", "", "", "", qt)
	if err != nil {
		return nil, nil, nil, err
	}
	m, err := s.measures(ctx, "", qt)
	if err != nil {
		return nil, nil, nil, err
	}
	p, err := s.phases(ctx, "", qt)
	return w, m, p, err
}
func (s *Store) visibilitySQL() string {
	if s.region != "" {
		return "true"
	}
	return `s.public_enabled AND EXISTS (SELECT 1 FROM retained_acquisitions pa JOIN registry_events pe ON pe.source_id=pa.source_id AND pe.revision=pa.configuration AND pe.kind='acceptance' WHERE pa.document_id=v.document_id AND pa.version_id=v.id)`
}
